CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE
    CURSOS (
        ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
        NOME VARCHAR(30) NOT NULL,
        HORAS INT (3) NOT NULL,
        VALOR FLOAT (10, 2) NOT NULL -- CABE 8 ANTES DA VIRGULA E 2 DEPOIS
    );

-- EM MYSQL LEMBRAR QUE PRIMARY KEY COMEÇA COM NULL
-- INSERT INTO
--     CURSOS
-- VALUES
--     (NULL, "Java", 30, 500.00),
--     (NULL, "Fundamento de Banco de dados", 40, 700.00);
-- SELECT * FROM CURSOS;

/* CRIANDO UMA PROCEDURE DE CADASTRO  */

DELIMITER $

CREATE PROCEDURE CAD_CURSO( P_CURSO_NAME VARCHAR(30), P_HORAS INT(3), P_VALOR FLOAT(10,2) )
BEGIN
    -- COMANDO PARA INSERIR NA TABELA
    INSERT INTO
        CURSOS
    VALUES
        (NULL, P_CURSO_NAME, P_HORAS, P_VALOR);

END$

DELIMITER ;

CALL CAD_CURSO("Curso de JavaScript", 50, 600.50);

/* CRIANDO UMA PROCEDURE PARA SELECIONAR DADOS */

DELIMITER $

CREATE PROCEDURE FIND_CURSO( P_CURSO_NAME VARCHAR(30), P_HORAS INT(3), P_VALOR FLOAT(10,2))
BEGIN 
    -- COMANDO PARA PESQUISAR
    SELECT NOME FROM CURSOS
    WHERE NOME = P_CURSO_NAME OR HORAS = P_HORAS OR VALOR = P_VALOR;
END$

DELIMITER ; 

CALL FIND_CURSO("Curso de JavaScript", 50,600.50);