CREATE TABLE PACIENTE (
    ID_PACIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SEXO ENUM('F', 'M') NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    NASCIMENTO DATE NOT NULL
);

CREATE TABLE MEDICO (
    ID_MEDICO INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    SEXO ENUM('F', 'M') NOT NULL,
    ESPECIALIDADE VARCHAR(50) NOT NULL,
    FUNCIONARIO ENUM('S', 'N') NOT NULL
);

CREATE TABLE HOSPITAL (
    ID_HOSPITAL INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    BAIRRO VARCHAR(30) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL,
    ESTADO CHAR(2) NOT NULL
);

CREATE TABLE CONSULTA (
    ID_CONSULTA INTEGER PRIMARY KEY AUTO_INCREMENT,
    FK_PACIENTE INTEGER NOT NULL,
    FK_MEDICO INTEGER NOT NULL,
    FK_HOSPITAL INTEGER NOT NULL,
    DATA DATETIME,
    DIAGNOSTICO VARCHAR(100) NOT NULL
);

CREATE TABLE INTERNACAO (
    ID_INTERNACAO INTEGER PRIMARY KEY AUTO_INCREMENT,
    FK_CONSULTA INTEGER NOT NULL,
    DATA_ENTRADA DATETIME NOT NULL,
    QUARTO INT NOT NULL,
    SAIDA DATETIME NOT NULL,
    OBSERVACAO VARCHAR(100)
);

ALTER TABLE CONSULTA ADD CONSTRAINT CONSTRAINT_FK_PACIENTE FOREIGN KEY (FK_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);
ALTER TABLE CONSULTA ADD CONSTRAINT CONSTRAINT_FK_MEDICO FOREIGN KEY (FK_MEDICO) REFERENCES MEDICO(ID_MEDICO);
ALTER TABLE CONSULTA ADD CONSTRAINT CONSTRAINT_FK_HOSPITAL FOREIGN KEY  (FK_HOSPITAL) REFERENCES HOSPITAL(ID_HOSPITAL);
ALTER TABLE INTERNACAO ADD CONSTRAINT CONSTRAINT_FK_CONSULTA FOREIGN KEY (FK_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA);